<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita51ba4651cb6eeab953a195d7666530e
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Ddeboer\\Transcoder\\Tests\\' => 25,
            'Ddeboer\\Transcoder\\' => 19,
            'Ddeboer\\Imap\\Tests\\' => 19,
            'Ddeboer\\Imap\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ddeboer\\Transcoder\\Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/ddeboer/transcoder/tests',
        ),
        'Ddeboer\\Transcoder\\' => 
        array (
            0 => __DIR__ . '/..' . '/ddeboer/transcoder/src',
        ),
        'Ddeboer\\Imap\\Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/ddeboer/imap/tests',
        ),
        'Ddeboer\\Imap\\' => 
        array (
            0 => __DIR__ . '/..' . '/ddeboer/imap/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita51ba4651cb6eeab953a195d7666530e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita51ba4651cb6eeab953a195d7666530e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
